[workspace]
members = ["haptic-protocol", "haptic-server", "haptic-plugin", "xtask"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
crossbeam-channel = "0.5"
parking_lot = "0.12"
rtrb = "0.3"